# Generated by Django 4.1.7 on 2023-06-26 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_address_user_default_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='place',
            field=models.CharField(max_length=50, verbose_name='详细地址'),
        ),
    ]
