# Generated by Django 4.1.7 on 2023-07-12 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_address_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='title',
            field=models.CharField(help_text='地址名称', max_length=20, verbose_name='地址名称'),
        ),
    ]
